#!/bin/bash

SC_CONTRACT_DOCKER_VERSION="${SC_CONTRACT_DOCKER_VERSION:-2.2.5.BUILD-SNAPSHOT}"
APP_IP="$( ./src/AspNetCoreExample/whats_my_ip.sh )"
STUBRUNNER_PORT="8083"

STUBRUNNER_API_PORT="9876"

STUBRUNNER_IDS="com.example:customer-service:0.0.1.RELEASE:stubs:9876"
STUBRUNNER_REPOSITORY_ROOT="http://${APP_IP}:8081/artifactory/libs-release-local"

docker run  --rm -e "STUBRUNNER_IDS=${STUBRUNNER_IDS}" -e "STUBRUNNER_REPOSITORY_ROOT=${STUBRUNNER_REPOSITORY_ROOT}" -e "STUBRUNNER_STUBS_MODE=REMOTE" -p "${STUBRUNNER_PORT}:${STUBRUNNER_PORT}" -p "${STUBRUNNER_API_PORT}:${STUBRUNNER_API_PORT}" springcloud/spring-cloud-contract-stub-runner:"${SC_CONTRACT_DOCKER_VERSION}"